# Generated by Django 5.0.6 on 2024-06-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lock', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.TextField(max_length=255)),
                ('user_name', models.TextField(max_length=255)),
                ('password', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
