# Generated by Django 5.0.6 on 2024-06-11 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lock', '0005_rename_date_service_create_date_service_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='service',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
